import { describe, expect, it } from "vitest";
import { CANARY, VERSION, canaryVersion, relockWorkspace, unreleasedSection } from "./manifests.ts";

const changelog = (heading: string): string =>
  `# Changelog\n\nIntro.\n\n${heading}\n\n- A change.\n\n## 0.1.1 (2026-10-02)\n\n- Earlier.\n`;

describe("canaryVersion", () => {
  it("bumps the patch version after the latest release", () => {
    expect(canaryVersion("0.1.1", changelog("## Unreleased"), 42)).toBe("0.1.2-next.42");
  });

  it("uses the version the unreleased section names", () => {
    expect(canaryVersion("0.1.1", changelog("## 0.2.0 (unreleased)"), 7)).toBe("0.2.0-next.7");
  });

  it("makes a version the release scripts accept, published under next", () => {
    const version = canaryVersion("1.9.9", changelog("## Unreleased"), 1);
    expect(version).toMatch(VERSION);
    expect(version).toMatch(CANARY);
    expect(version).toContain("-");
  });

  it("refuses a pre-release, a bad run number, and a changelog without an unreleased section", () => {
    const unreleased = changelog("## Unreleased");
    expect(() => canaryVersion("0.1.2-next.3", unreleased, 4)).toThrow(/released version/);
    expect(() => canaryVersion("0.1.1", unreleased, 0)).toThrow(/run number/);
    expect(() => canaryVersion("0.1.1", unreleased, Number.NaN)).toThrow(/run number/);
    expect(() => canaryVersion("0.1.1", changelog("## 0.1.2 (2026-10-09)"), 4)).toThrow(
      /Unreleased/,
    );
  });
});

describe("unreleasedSection", () => {
  it("finds the section, and the version it names", () => {
    expect(unreleasedSection(changelog("## Unreleased"))).toEqual({ version: undefined });
    expect(unreleasedSection(changelog("## 0.3.0 (unreleased)"))).toEqual({ version: "0.3.0" });
    expect(unreleasedSection(changelog("## 0.3.0 (2026-10-09)"))).toBeUndefined();
  });
});

describe("relockWorkspace", () => {
  const lock = [
    "# This file is automatically @generated by Cargo.",
    "version = 4",
    "",
    "[[package]]",
    'name = "serde"',
    'version = "0.1.1"',
    'source = "registry+https://github.com/rust-lang/crates.io-index"',
    "",
    "[[package]]",
    'name = "tessera-cli"',
    'version = "0.1.1"',
    "dependencies = [",
    ' "serde",',
    "]",
    "",
    "[[package]]",
    'name = "tessera-core"',
    'version = "0.1.1"',
    "",
  ].join("\n");

  it("moves the workspace's crates and leaves registry crates alone", () => {
    const relocked = relockWorkspace(lock, "0.1.1", "0.1.2-next.5");
    expect(relocked.match(/version = "0\.1\.2-next\.5"/g)).toHaveLength(2);
    expect(relocked).toMatch(/name = "serde"\nversion = "0\.1\.1"\nsource/);
    expect(relocked).toMatch(/^version = 4$/m);
  });

  it("keeps Windows line endings", () => {
    const relocked = relockWorkspace(lock.replaceAll("\n", "\r\n"), "0.1.1", "0.1.2-next.5");
    expect(relocked).toBe(relockWorkspace(lock, "0.1.1", "0.1.2-next.5").replaceAll("\n", "\r\n"));
  });
});
