// Regenerates `table.rs` and `fixtures/*.json` from the real `github-slugger`.
//
//   npm install --prefix <tmp> github-slugger@2.0.0
//   NODE_PATH=<tmp>/node_modules node generate.mjs
//
// The Rust port is checked against this package's actual output, so run this
// against the version recorded in `mod.rs` and commit the result.
import { createRequire } from 'node:module'
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const req = createRequire(join(process.env.NODE_PATH ?? '.', 'x.js'))
const pkgDir = dirname(req.resolve('github-slugger/package.json'))
const pkg = req('github-slugger/package.json')
const { default: GithubSlugger, slug } = await import(
  pathToFileURL(join(pkgDir, 'index.js')).href
)
const { regex } = await import(pathToFileURL(join(pkgDir, 'regex.js')).href)

// Removed scalar values, as ranges. The upstream regex is written over UTF-16
// code units with explicit surrogate-pair alternatives, so testing one whole
// scalar at a time is exact. (Lone surrogates can't occur in a Rust `str`.)
const removed = []
for (let cp = 0; cp <= 0x10ffff; cp++) {
  if (cp >= 0xd800 && cp <= 0xdfff) continue
  regex.lastIndex = 0
  const s = String.fromCodePoint(cp)
  const gone = s.replace(regex, '') === ''
  if (gone) {
    const last = removed[removed.length - 1]
    if (last && last[1] === cp - 1) last[1] = cp
    else removed.push([cp, cp])
  }
}
const hex = (n) => '0x' + n.toString(16).toUpperCase().padStart(4, '0')
let rs = `// @generated by generate.mjs from github-slugger ${pkg.version}. Do not edit.\n\n`
rs += `/// The scalar values \`github-slugger\` ${pkg.version} removes after lowercasing, as\n`
rs += `/// inclusive \`(first, last)\` ranges in ascending order.\n`
rs += `pub(super) const REMOVED: &[(u32, u32)] = &[\n`
for (const [a, b] of removed) rs += `    (${hex(a)}, ${hex(b)}),\n`
rs += `];\n`
writeFileSync(join(here, 'table.rs'), rs)

// Per-scalar behaviour beyond "removed or kept as is": the slug of every
// scalar whose slug is neither itself nor empty (lowercase mappings, space).
const mapped = []
for (let cp = 0; cp <= 0x10ffff; cp++) {
  if (cp >= 0xd800 && cp <= 0xdfff) continue
  const s = String.fromCodePoint(cp)
  const out = slug(s)
  if (out !== '' && out !== s) mapped.push([cp, out])
}
writeFileSync(join(here, 'fixtures/scalars.json'), JSON.stringify({ version: pkg.version, mapped }) + '\n')

// Hand-picked inputs.
const inputs = [
  '', ' ', '  ', '-', '--', '_', '__init__', 'foo', 'Foo', 'FOO', 'foo bar', 'foo  bar', ' foo ', 'foo-bar',
  'foo_bar', 'foo.bar', 'foo/bar', 'foo:bar', 'foo\tbar', 'foo\nbar', 'foo bar', 'foo bar',
  'Getting started', 'Getting Started!', 'What is Tessera?', "What's new in 1.0?", 'C++ and C#',
  'Q&A', '100% sure', '$HOME and ~/bin', '`code` in heading', '<div>', '[link](url)', '(parens) {braces}',
  'a, b; c: d', '"quoted" \'single\'', 'a@b.c', 'a=b', 'a+b', 'a|b', 'a\\b', 'a^b', 'a`b', 'a~b',
  '1. Numbered', '2024-01-01', '3.14', 'v1.2.3 release',
  'Ünicode', 'ÜBER', 'Ça va?', 'naïve café', 'straße', 'İstanbul', 'ǅ', 'ﬃ', 'ẞ', 'ΑΣ', 'ΟΔΥΣΣΕΥΣ', 'Σ',
  'Привет мир', 'Ёлка', 'ДА-НЕТ', 'Ελληνικά', 'עברית', 'שלום עולם', 'مرحبا بالعالم', 'हिन्दी भाषा',
  '日本語の見出し', '你好，世界', '你好 世界！', '한국어 제목', 'ไทย', 'தமிழ்', 'ქართული',
  '🎉', '🎉 Party', 'Party 🎉', 'A 🎉 B', '🇺🇸 flag', '👨‍👩‍👧 family', '❤️ heart', '✅ Done', '⚠️ Warning',
  '👍🏽', '#️⃣ keycap', '™ ® ©', '«guillemets»', '“smart” ‘quotes’', '– en — em … ellipsis',
  '×÷', '¡Hola!', '¿Qué?', '€5', '£ ¥ ¢', '§ ¶', '‰', '′″',
  'é', 'a​b', 'a‍b', 'a﻿b', '\u0000a', 'a\u001Fb', '\u007F', '\u0080', ' ',
  '𝒜𝒷', '𐐀', '𠀀', '\u{E0001}', '\u{10FFFF}', '\u{1D7CE}',
  '(!) ', '!!!', '???', '...', '---', '- - -', '.-.', '$$$', '(())', '{}[]', '№', '⓪①', '½ ⅓', '²³',
  'ǈ', 'ǰ', 'ᾈ', 'ⅷ', 'Ⅷ', 'ⓐ', 'Ⓐ',
]

// Duplicate sequences, numbered by one scope.
const sequences = [
  ['intro', 'intro', 'intro'],
  ['intro', 'intro', 'intro', 'intro'],
  ['Intro', 'intro', 'INTRO'],
  ['a', 'a-1', 'a'],
  ['a-1', 'a', 'a'],
  ['a', 'a', 'a-1'],
  ['a', 'a', 'a-1', 'a-1', 'a'],
  ['a-1', 'a-1', 'a-1'],
  ['a-2', 'a', 'a', 'a', 'a'],
  ['', '', ''],
  ['!', '?', ' '],
  ['-', '-', '-'],
  ['🎉', '🎉', '🎉 '],
  ['你好', '你好', '你好'],
  ['1', '1', '1-1', '1'],
  ['a b', 'a-b', 'a  b', 'A B'],
  ['Setup', 'Install', 'Setup', 'Install', 'Setup', 'Usage', 'Usage'],
  ['x', 'x-1', 'x-2', 'x', 'x-1', 'x'],
]

// Seeded mixed strings, to catch anything the lists above miss.
let seed = 0x2f6e2b1
const rnd = (n) => {
  seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0
  return seed % n
}
const pools = [
  [...'abcdefghijklmnopqrstuvwxyz'], [...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'], [...'0123456789'],
  [...' -_ -_.,:;!?()[]{}<>/\\|@#$%^&*+=~`\'"'], [...'éÉüÜñÑøØßçÇåÅ'], [...'ΑΒΓΔΣσςαβγ'],
  [...'АБВГДЕЖабвгде'], [...'日本語中文한국어'], [...'مرحباשלום'], [...'🎉🚀✅❤️👍🇺🇸👨‍👩'],
  [...'́̈​‍  ﻿'], [...'𝒜𝐀𐐀𠀀'], [...'İǅﬃẞΣ'],
]
const random = []
for (let i = 0; i < 400; i++) {
  const len = 1 + rnd(24)
  let s = ''
  for (let j = 0; j < len; j++) {
    const p = pools[rnd(pools.length)]
    s += p[rnd(p.length)]
  }
  random.push(s)
}
// A few random dense-scalar strings drawn from the whole of Unicode.
for (let i = 0; i < 200; i++) {
  let s = ''
  for (let j = 0; j < 12; j++) {
    let cp
    do cp = rnd(0x110000)
    while (cp >= 0xd800 && cp <= 0xdfff)
    s += String.fromCodePoint(cp)
  }
  random.push(s)
}

const cases = [...inputs, ...random].map((input) => ({ input, slug: slug(input) }))
const dupes = sequences.map((inputs) => {
  const s = new GithubSlugger()
  return { inputs, slugs: inputs.map((t) => s.slug(t)) }
})
writeFileSync(join(here, 'fixtures/slugs.json'), JSON.stringify({ version: pkg.version, cases, dupes }, null, 1) + '\n')
console.log(`github-slugger ${pkg.version}: ${removed.length} ranges, ${mapped.length} mapped, ${cases.length} cases`)
