//! The Zod schema of a content model's frontmatter (SPEC §9.6): a TypeScript
//! module Astro's content collections take as their `schema`.
//!
//! [`generate`] writes one schema per content type, with the reserved
//! `available` and `variant` keys added. The schemas
//! describe the frontmatter the site output writes, not the source's: in
//! particular `available` is the list of targets the site emitter writes,
//! not the spec string an author wrote.
//!
//! The module imports `z` from `astro/zod`, which is Zod 4 in the Astro
//! version the site output targets (7.3, [`crate::site::ASTRO_VERSION`]). Unknown
//! keys are rejected, as they are in Ascribe (`frontmatter-unknown-key`), with
//! `z.strictObject`.
//!
//! # What it exports
//!
//! For a type named `reference-guide`:
//!
//! - `referenceGuideSchema`: its Zod object, and the type `ReferenceGuide`;
//! - `schemas`: every type's schema by its name;
//! - `contentTypes`: for each type, its `files` patterns and whether it's
//!   the default, for a collection configuration that loads each type's
//!   pages;
//! - `schema`: a schema that accepts the frontmatter of any type, for a
//!   collection that holds them all.
//!
//! It also exports `availableSchema` and `variantSchema`, for layouts.
//!
//! A type with fields that set `inline = "code"` also has `formatted`: each
//! such field's formatted form, as HTML, which the site output writes beside
//! the field's plain text.

use std::fmt::Write as _;

use ascribe_core::names;
use ascribe_model::{ContentModel, ContentType, Field, FieldType, inline};
use serde_yaml_ng::Value;

/// The Zod module for a content model.
pub fn generate(model: &ContentModel) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str(
        &RESERVED
            .replace("{availability-target}", names::ELEMENT_AVAILABILITY_TARGET)
            .replace("{availability}", names::ELEMENT_AVAILABILITY),
    );
    let mut names = Vec::new();
    for ty in &model.types {
        let ident = identifier(&ty.name);
        names.push((ty.name.clone(), ident.clone()));
        let _ = write!(
            out,
            "\n/** The frontmatter of pages of type `{}`. */\n",
            ty.name
        );
        let _ = writeln!(
            out,
            "export const {ident}Schema = {};",
            object(&ty.frontmatter.fields, true, 0)
        );
        let _ = writeln!(
            out,
            "export type {} = z.infer<typeof {ident}Schema>;",
            capitalize(&ident)
        );
    }
    out.push_str("\n/** Every content type's schema, by the type's name. */\n");
    out.push_str("export const schemas = {\n");
    for (name, ident) in &names {
        let _ = writeln!(out, "  {}: {ident}Schema,", key(name));
    }
    out.push_str("} as const;\n");
    out.push_str("\n/** Which pages each content type applies to. */\n");
    out.push_str("export const contentTypes = {\n");
    for ty in &model.types {
        let _ = writeln!(out, "  {}: {},", key(&ty.name), type_info(ty));
    }
    out.push_str("} as const;\n");
    out.push_str("\n/** A schema that accepts the frontmatter of any content type. */\n");
    match names.as_slice() {
        [] => out.push_str("export const schema = z.never();\n"),
        [(_, only)] => {
            let _ = writeln!(out, "export const schema = {only}Schema;");
        }
        many => {
            out.push_str("export const schema = z.union([\n");
            for (_, ident) in many {
                let _ = writeln!(out, "  {ident}Schema,");
            }
            out.push_str("]);\n");
        }
    }
    out
}

const HEADER: &str = "\
// Generated by `ascribe build --emit site` from ascribe.toml. Don't edit it:
// change the content model and build again.
//
// The Zod schemas of the frontmatter in the site output, for an Astro content
// collection's `schema`. Written for Astro 7.3 (Zod 4, from `astro/zod`).

import { z } from \"astro/zod\";
";

/// The reserved keys: `available` as the site output writes it (element
/// contract §4), and `variant` as written (SPEC §4.3). `{availability}` and
/// `{availability-target}` stand for the elements' names.
const RESERVED: &str = "
/** One target of a page's availability: the attributes of a
 * `<{availability-target}>`, and the text it shows. */
export const availableTargetSchema = z.strictObject({
  target: z.string(),
  dimension: z.string(),
  states: z.array(z.string()),
  versions: z.array(z.string()).optional(),
  text: z.string(),
});

/** A page's availability, for a layout to show with
 * `<{availability} scope=\"page\">`. */
export const availableSchema = z.array(availableTargetSchema);
export type Available = z.infer<typeof availableSchema>;

/** The dimension values a page applies to (SPEC §4.3). */
export const variantSchema = z.record(
  z.string(),
  z.union([z.string(), z.array(z.string())]),
);
export type Variant = z.infer<typeof variantSchema>;
";

/// `{ default: true, files: [...] }` for a content type.
fn type_info(ty: &ContentType) -> String {
    let files: Vec<String> = ty.files.iter().map(|p| json(p.as_str())).collect();
    format!(
        "{{ default: {}, files: [{}] }}",
        ty.default,
        files.join(", ")
    )
}

/// A `z.strictObject`, with its lines indented by `base` spaces after the
/// first: unknown keys are errors, as they are in Ascribe. With `reserved`,
/// the reserved keys are added.
fn object(fields: &[Field], reserved: bool, base: usize) -> String {
    let inner = " ".repeat(base + 2);
    let mut out = String::from("z.strictObject({\n");
    for field in fields {
        let _ = writeln!(
            out,
            "{inner}{}: {},",
            key(&field.name),
            field_schema(field, base + 2)
        );
    }
    if reserved {
        let _ = writeln!(out, "{inner}available: availableSchema.optional(),");
        let _ = writeln!(out, "{inner}variant: variantSchema.optional(),");
        let formatted: Vec<&Field> = fields.iter().filter(|f| f.inline.is_some()).collect();
        if !formatted.is_empty() {
            let _ = writeln!(
                out,
                "{inner}formatted: {},",
                formatted_schema(&formatted, base + 2)
            );
        }
    }
    let _ = write!(out, "{}}})", " ".repeat(base));
    out
}

/// `formatted`: the HTML of each `inline` field, there whenever the field
/// has a value, its own or its default.
fn formatted_schema(fields: &[&Field], base: usize) -> String {
    let inner = " ".repeat(base + 2);
    let mut out = String::from("z.strictObject({\n");
    let mut any_required = false;
    for field in fields {
        let present = field.required || field.default.is_some();
        any_required |= present;
        let optional = if present { "" } else { ".optional()" };
        let _ = writeln!(out, "{inner}{}: z.string(){optional},", key(&field.name));
    }
    let _ = write!(out, "{}}})", " ".repeat(base));
    if !any_required {
        out.push_str(".optional()");
    }
    out
}

/// An object key, bare when it's a valid identifier.
fn key(name: &str) -> String {
    let mut chars = name.chars();
    let bare = chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_' || c == '$')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
    if bare { name.to_owned() } else { json(name) }
}

/// The Zod schema of a field: its type, optionality, default, and help text.
fn field_schema(field: &Field, base: usize) -> String {
    let mut out = type_schema(&field.ty, base);
    if let Some(default) = &field.default {
        // The site output writes an `inline` field as its plain text.
        let plain;
        let default = match (field.inline, default) {
            (Some(_), Value::String(text)) => {
                plain = Value::String(inline::plain_text(&inline::parse(text, &|_| None)));
                &plain
            }
            _ => default,
        };
        let _ = write!(out, ".default({})", default_value(&field.ty, default));
    } else if !field.required {
        out.push_str(".optional()");
    }
    if let Some(description) = &field.description {
        let _ = write!(out, ".describe({})", json(description));
    }
    out
}

fn type_schema(ty: &FieldType, base: usize) -> String {
    match ty {
        FieldType::String => "z.string()".to_owned(),
        FieldType::Number => "z.number()".to_owned(),
        FieldType::Boolean => "z.boolean()".to_owned(),
        // A date is written `YYYY-MM-DD`; YAML readers may hand it over as a
        // string or as a date, and Astro's docs use `z.coerce.date()`.
        FieldType::Date => "z.coerce.date()".to_owned(),
        FieldType::Enum(values) if values.is_empty() => "z.string()".to_owned(),
        FieldType::Enum(values) => {
            let list: Vec<String> = values.iter().map(|v| json(v)).collect();
            format!("z.enum([{}])", list.join(", "))
        }
        FieldType::List(inner) => format!("z.array({})", type_schema(inner, base)),
        FieldType::Object(fields) => object(fields, false, base),
    }
}

/// A default as a TypeScript expression.
fn default_value(ty: &FieldType, value: &Value) -> String {
    match (ty, value) {
        (FieldType::Date, Value::String(s)) => format!("() => new Date({})", json(s)),
        _ => literal(value),
    }
}

/// A YAML value as a JavaScript literal.
fn literal(value: &Value) -> String {
    match value {
        Value::Null => "null".to_owned(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => json(s),
        Value::Sequence(items) => {
            let items: Vec<String> = items.iter().map(literal).collect();
            format!("[{}]", items.join(", "))
        }
        Value::Mapping(map) => {
            let pairs: Vec<String> = map
                .iter()
                .map(|(k, v)| {
                    let key = match k {
                        Value::String(s) => json(s),
                        other => json(serde_yaml_ng::to_string(other).unwrap_or_default().trim()),
                    };
                    format!("{key}: {}", literal(v))
                })
                .collect();
            format!("{{ {} }}", pairs.join(", "))
        }
        Value::Tagged(t) => literal(&t.value),
    }
}

/// A string as a JavaScript string literal.
fn json(text: &str) -> String {
    serde_json::to_string(text).unwrap_or_else(|_| "\"\"".to_owned())
}

/// A type's name as a JavaScript identifier: `reference-guide` is
/// `referenceGuide`.
fn identifier(name: &str) -> String {
    let mut out = String::new();
    let mut upper = false;
    for ch in name.chars() {
        if ch == '-' {
            upper = true;
        } else if upper {
            out.extend(ch.to_uppercase());
            upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn capitalize(ident: &str) -> String {
    let mut chars = ident.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names_become_identifiers() {
        assert_eq!(identifier("page"), "page");
        assert_eq!(identifier("reference-guide"), "referenceGuide");
        assert_eq!(capitalize("referenceGuide"), "ReferenceGuide");
    }

    #[test]
    fn values_become_literals() {
        assert_eq!(json("a \"b\"\n"), "\"a \\\"b\\\"\\n\"");
        assert_eq!(
            literal(&serde_yaml_ng::from_str("[1, two, true]").unwrap_or_default()),
            "[1, \"two\", true]"
        );
    }
}
