import { defineCollection } from "astro:content";
import { ascribeCollection } from "@ascribed/astro/content";
// Generated by `ascribe build --emit site`, which the integration runs first.
import { schema } from "../../docs/.ascribe/build/site/site/_ascribe/schema.ts";

export const collections = { docs: defineCollection(ascribeCollection({ schema })) };
