import { defineCollection } from "astro:content";
import { ascribeCollection } from "@ascribed/astro/content";
// Generated by `ascribe build --emit site`, which the integration runs first,
// and copied inside this folder, where TypeScript finds `astro/zod`.
import { schema } from "../.astro/integrations/_ascribed_astro/schema.ts";

export const collections = { docs: defineCollection(ascribeCollection({ schema })) };
