//! A generated block between two marker lines, in a file whose other text
//! is the team's:
//!
//! ```markdown
//! <!-- ascribe:agents start (generated by `ascribe agents sync`; …) -->
//! …
//! <!-- ascribe:agents end -->
//! ```
//!
//! Placing a block replaces what's between a file's markers, or appends the
//! block to a file that has none, and never changes a byte outside them.

/// What's wrong with a file's markers, so its block can't be placed.
#[derive(Clone, Copy, Debug, PartialEq, Eq, thiserror::Error)]
pub enum Damage {
    /// A start marker with no end marker after it.
    #[error("its start marker has no end marker after it")]
    NoEnd,
    /// An end marker with no start marker before it.
    #[error("its end marker has no start marker before it")]
    NoStart,
    /// More than one start or end marker.
    #[error("it has more than one start or end marker")]
    Twice,
}

/// A block's markers: `name` tells one block from another in the same file
/// (`ascribe:agents`, `ascribe:agents:docs`), and `note` is what the start
/// marker says in brackets.
#[derive(Clone, Copy, Debug)]
pub struct Markers<'a> {
    /// The block's name.
    pub name: &'a str,
    /// What the start marker says after its name.
    pub note: &'a str,
}

impl Markers<'_> {
    fn start(&self) -> String {
        format!("<!-- {} start ({}) -->", self.name, self.note)
    }

    fn end(&self) -> String {
        format!("<!-- {} end -->", self.name)
    }

    fn is_start(&self, line: &str) -> bool {
        let prefix = format!("<!-- {} start", self.name);
        line.strip_prefix(&prefix)
            .is_some_and(|rest| rest == " -->" || (rest.starts_with(' ') && rest.ends_with("-->")))
    }

    fn is_end(&self, line: &str) -> bool {
        line == self.end()
    }

    /// The block holding `body`, with `newline` ending each line.
    fn block(&self, body: &str, newline: &str) -> String {
        let mut out = self.start();
        out.push_str(newline);
        for line in body.lines() {
            out.push_str(line);
            out.push_str(newline);
        }
        out.push_str(&self.end());
        out.push_str(newline);
        out
    }

    /// `text` (a file's, or `None` for no file) with this block holding
    /// `body`: between its markers, or appended after a blank line. Lines
    /// end as the file's first line does.
    pub fn place(&self, text: Option<&str>, body: &str) -> Result<String, Damage> {
        let Some(text) = text else {
            return Ok(self.block(body, "\n"));
        };
        let newline = match text.find('\n') {
            Some(at) if text[..at].ends_with('\r') => "\r\n",
            _ => "\n",
        };
        let mut starts = Vec::new();
        let mut ends = Vec::new();
        let mut offset = 0;
        for line in text.split_inclusive('\n') {
            let trimmed = line.trim();
            if self.is_start(trimmed) {
                starts.push(offset);
            } else if self.is_end(trimmed) {
                ends.push(offset + line.len());
            }
            offset += line.len();
        }
        match (starts.as_slice(), ends.as_slice()) {
            ([], []) => {
                let mut out = text.to_owned();
                if !out.is_empty() {
                    if !out.ends_with('\n') {
                        out.push_str(newline);
                    }
                    out.push_str(newline);
                }
                out.push_str(&self.block(body, newline));
                Ok(out)
            }
            ([start], [end]) if start < end => Ok(format!(
                "{}{}{}",
                &text[..*start],
                self.block(body, newline),
                &text[*end..]
            )),
            ([_], [_]) | ([], [_]) => Err(Damage::NoStart),
            ([_], []) => Err(Damage::NoEnd),
            _ => Err(Damage::Twice),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const MARKERS: Markers<'static> = Markers {
        name: "ascribe:agents",
        note: "generated",
    };

    #[test]
    fn a_missing_file_gets_only_the_block() {
        assert_eq!(
            MARKERS.place(None, "Hello.\n"),
            Ok(
                "<!-- ascribe:agents start (generated) -->\nHello.\n<!-- ascribe:agents end -->\n"
                    .to_owned()
            )
        );
    }

    #[test]
    fn a_file_without_markers_gets_the_block_after_a_blank_line() {
        let placed = MARKERS.place(Some("# Rules\n\nBe kind."), "Hello.\n");
        assert_eq!(
            placed,
            Ok("# Rules\n\nBe kind.\n\n<!-- ascribe:agents start (generated) -->\nHello.\n<!-- ascribe:agents end -->\n".to_owned())
        );
    }

    #[test]
    fn text_around_the_markers_survives_byte_for_byte() {
        let text = "# Rules  \n\n<!-- ascribe:agents start (old note) -->\nOld.\n<!-- ascribe:agents end -->\n\nMore rules, no newline";
        let placed = MARKERS.place(Some(text), "New.\n").unwrap_or_default();
        assert_eq!(
            placed,
            "# Rules  \n\n<!-- ascribe:agents start (generated) -->\nNew.\n<!-- ascribe:agents end -->\n\nMore rules, no newline"
        );
        assert_eq!(MARKERS.place(Some(&placed), "New.\n"), Ok(placed.clone()));
    }

    #[test]
    fn a_crlf_file_keeps_crlf() {
        let text = "# Rules\r\n\r\n<!-- ascribe:agents start (x) -->\r\nOld.\r\n<!-- ascribe:agents end -->\r\n";
        assert_eq!(
            MARKERS.place(Some(text), "One.\nTwo.\n"),
            Ok("# Rules\r\n\r\n<!-- ascribe:agents start (generated) -->\r\nOne.\r\nTwo.\r\n<!-- ascribe:agents end -->\r\n".to_owned())
        );
        assert_eq!(
            MARKERS.place(Some("# Rules\r\n"), "One.\n"),
            Ok("# Rules\r\n\r\n<!-- ascribe:agents start (generated) -->\r\nOne.\r\n<!-- ascribe:agents end -->\r\n".to_owned())
        );
    }

    #[test]
    fn other_blocks_are_other_blocks() {
        let text =
            "<!-- ascribe:agents:docs start (x) -->\nDocs.\n<!-- ascribe:agents:docs end -->\n";
        let placed = MARKERS.place(Some(text), "Mine.\n").unwrap_or_default();
        assert!(placed.starts_with(text), "{placed}");
        assert!(
            placed.ends_with("Mine.\n<!-- ascribe:agents end -->\n"),
            "{placed}"
        );
    }

    #[test]
    fn damaged_markers_are_refused() {
        let start = "<!-- ascribe:agents start (x) -->\n";
        let end = "<!-- ascribe:agents end -->\n";
        assert_eq!(MARKERS.place(Some(start), ""), Err(Damage::NoEnd));
        assert_eq!(MARKERS.place(Some(end), ""), Err(Damage::NoStart));
        assert_eq!(
            MARKERS.place(Some(&format!("{end}{start}")), ""),
            Err(Damage::NoStart)
        );
        assert_eq!(
            MARKERS.place(Some(&format!("{start}{end}{start}{end}")), ""),
            Err(Damage::Twice)
        );
    }
}
