import { defineCollection } from "astro:content";
import { ascribeCollection } from "@ascribed/astro/content";
// Generated by `ascribe build --emit site`; the integration runs it first.
import { schema } from "../.ascribe/build/site/site/_ascribe/schema.ts";

export const collections = {
  docs: defineCollection(ascribeCollection({ schema })),
};
