import { defineCollection } from "astro:content";
import { tesseraCollection } from "@tessera/astro/content";
// Generated by `ascribe build --emit site`; the integration runs it first.
import { schema } from "../.tessera/build/site/site/_tessera/schema.ts";

export const collections = {
  docs: defineCollection(tesseraCollection({ schema })),
};
